export const FETCH_PRODUCTS_BY_NAME = 'FETCH_PRODUCTS_BY_NAME'
export const SELECT_PRODUCT = 'SELECT_PRODUCT'
export const SELECT_SIMILAR_PRODUCTS = 'SELECT_SIMILAR_PRODUCTS'
export const CREATE_PRODUCT= 'CREATE_PRODUCT';
export const GET_GRAPES= 'GET_GRAPES';
export const FETCH_ALL_CELLARS= 'FETCH_ALL_CELLARS';
export const FETCH_ALL_LINES= 'FETCH_ALL_LINES';
export const FETCH_SELECTEDGRAPES= 'FETCH_SELECTEDGRAPES';
export const PRODUCT_UPDATED= 'PRODUCT_UPDATED';
export const LOG_A_USER= 'LOG_A_USER';
export const LOGOUT_USER= 'LOGOUT_USER';
export const FETCH_ORDERS= 'FETCH_ORDERS';
export const FETCH_USERS= 'FETCH_USERS';
export const SET_CART= 'SET_CART';
export const ADD_TO_ORDER= 'ADD_TO_ORDER';
export const REMOVE_FROM_ORDER = 'REMOVE_FROM_ORDER';
export const DELETE_FROM_ORDER= 'DELETE_FROM_ORDER';
export const ADD_STORAGE_TO_STATE= 'ADD_STORAGE_TO_STATE';
export const EMPTY_CART= 'EMPTY_CART';

// Render inicial:
export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS'